### PR TITLE
Added metadata tag.

### PR DESCRIPTION
**Pull request by kalaspuffar**
Issue https://github.com/mtmse/dotify.formatter.impl/issues/25

Description:
Enable the addition of a metadata tag in OBFL to have it available in the PEF output.

Changes:
* Added metadata as a possible child to row.

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Hi @bertfrees and @PaulRambags

Please review this PR. It is connected to the issue above, and the actual implementation is in the formatter.

Best regards
Daniel

**Comment by bertfrees** [comment]
@kalaspuffar I agree with Paul that we should consider not changing the PEF spec if not really needed. I don't think we currently have a use case for storing the kind of information in a PEF file that you can represent with this new element. Your use case is to synchronize text and braille documents in your editor. You are probably not using PEF for that. If the user of the editor requests to save the braille document as a PEF, that synchronization info doesn't need to be present. It is useless information for the embosser that the user will send the PEF to, and there is even a risk that the embosser will choke on it.

If we decide to change PEF we should make sure we create a new version and make the desired PEF version a Dotify setting.

Note that there is a (very brief) section in PEF 1.0 that [allows the use of other namespaces](https://mtmse.github.io/pef/pef-specification.html#Using). Maybe this is a safer and more appropriate way to extend PEF? The section is really vague though so I don't know how exactly this was envisioned to work. We could ask Joel/Björn.

**Comment by bertfrees** [comment]
> Note that there is a (very brief) section in PEF 1.0 that allows the use of other namespaces.

Because in your implementation you are attaching the metadata to rows, not in between characters, it is maybe sufficient to allow any attributes with a foreign namespace on the row element. And if I understand the PEF specification correctly this is already allowed.

**Comment by kalaspuffar** [comment]
Hi @bertfrees 

The first implementation added metadata attributes to the rows and if that is already supported then I will close this merge request and change the implementation to add the information to the row instead of adding an extra element.

Best regards
Daniel

**Pull request closed without merging**
